// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPxDlEbV3J6RlGcM8cgvtmF5m44fChEi0',
    appId: '1:676568236832:web:9303a2b4f5e92269218d45',
    messagingSenderId: '676568236832',
    projectId: 'e-commerce-mans',
    authDomain: 'e-commerce-mans.firebaseapp.com',
    storageBucket: 'e-commerce-mans.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqGTEeKlGuxG3PUUJsK6iPQAefSsCsHPQ',
    appId: '1:676568236832:android:256c351f17852e99218d45',
    messagingSenderId: '676568236832',
    projectId: 'e-commerce-mans',
    storageBucket: 'e-commerce-mans.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeNcrg2UUI_xP3FAJF2sf_GWgfkMKRbG4',
    appId: '1:676568236832:ios:5c13a8990d8f5579218d45',
    messagingSenderId: '676568236832',
    projectId: 'e-commerce-mans',
    storageBucket: 'e-commerce-mans.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeNcrg2UUI_xP3FAJF2sf_GWgfkMKRbG4',
    appId: '1:676568236832:ios:172162028ec984b0218d45',
    messagingSenderId: '676568236832',
    projectId: 'e-commerce-mans',
    storageBucket: 'e-commerce-mans.appspot.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
